language: go

services:
  - docker

go:
- 1.8
- 1.x

env:
  global:
  - REPO="codem8s/oauth2-proxy"
  - VERSION=0.0.1
  - COMMIT=${TRAVIS_COMMIT::6}
  - SOURCE_FOLDER=${HOME}/gopath/src/github.com/bitly/oauth2_proxy
  # Quay user
  - secure: "7RZ4mUS9aeVjkaKMd2OOvMF+sthY+3/S9b35c3BpXYsGrrUHHrHuA4RSuN3f++pQ6EOkQnMWZfzeL739pRgEmaCEYm+qpJJPCpUsB/Gu762vmJnZldBP0MxLrBi/uOGJjecwSbhzApKRv9ecK4fdt1ZnUMflDyriAsJoH6G1NP2ArgIM8ehdtAAVcG9omPkb3ZaXhtCU+6Tdsj5pJHP4YfeHMuMWF8pDb9z0MWykMeoR1r0hpjRrFVXRKDrN11dtmdql5iKRwtPB9S54Fjcl1o7Ed7bMEYYcAKvgeshzKteyxJY9die+XCKpQfKlynfNFpZDn2sc/nA72jLlCei/MTF3iBGcNT9/qWJZGFYdkU4pfpc22yWdgjmChZ1HujUI3WBc4NiuD404SBdiLCa2MCkSx5vQVKB7utvXhbn4A91FYPbL/rsuPL6DZqHbLbopcNWOaLgHvvrJd/XLKMgc6NB6Q5yI4tzUjRzSvVTqrp72zCwoTxV85LIebDWwGXFNJIyB1MetdpcbghqHRM7bZvWPkCkxxiR1ISqPe4aqOI5uF0BYXgLLRg6DnrZxygN1rlqd45hFo8L8IYjZBlheCpZ5viIq8OCIuOg0RjPV2d7plrJNHlLY4HT6cY5QW3bJpkr/5ScaScYDHqgbyphIMJBeTK7C6PonEsELZJfzBNc="
  # Quay pass
  - secure: "gRR+ZKP2YNeeTg5LsXZH9U7DpLpA3itHCNJ9kY/52DfG89EOoZNW0Vgc/xXE4tdWjzRAtJlCUgqfjTpVb4pNQA4LeIpJiJ9VgsAmVUxAGuznKjrv9B33uyKFYNCBvZYXO3zz6KyVXmVE6UMEIDi7M2rfyRgZjmPym/DjiVOTsHMHWMrA47l7BScGUjts1uwn11lmXX4BCMLkaz701vxyiDEXt9RQceCyL3VO+bxeDwxLZQt4v+Vohazn7tUYR9r+FtupeBNc+oRHeHMv7/90oKZx92d9zI7QRup1g4+RGJNmiUpm/tKNC89winBhZcFvsUdLRr4fgG/A8zAaPQOR4Gy/owNuAnNC3HuieZrMrmHcTDyQR5cEDIVQy4sWwqXb9S71Qr+CEWqbKvZ9k+KRR4SADzueXcevH3sf5QEy86QWf+IvP90dwRJsgipTY1Jr9n49uPtld+pfzvEPIMJRlejxbm6hd/rlQ5W2vPDxAHEeMsR5xeVO3MO2j6QQ0S8kmD7VGrKZJXGJj7/AzqzzVWo8wujNobBIIqDHig/NaHBpvwVhy1lBeSK3PwADsJsoIeIZVy3lSPdluTlhFJWy88gCeCQh5WKqf5iQEvrzuBSLV8lPaw8O0TOPgiNv45lJKLDYEsJ4byOckVbOtLFPV16G9K1LiT/lx8dcrv2lQTc="

matrix:
  fast_finish: true

before_install:
- mkdir -p ${SOURCE_FOLDER}
- rsync -az ${TRAVIS_BUILD_DIR}/ ${SOURCE_FOLDER}
- cd ${SOURCE_FOLDER}
- go get -u github.com/golang/dep/cmd/dep

install:
- dep ensure

before_script:
- go get -u github.com/golang/dep/cmd/dep
- go get -u github.com/golang/lint/golint
- go get -u golang.org/x/tools/cmd/goimports
- go get -u golang.org/x/tools/cmd/godoc

script:
- "./test.sh"
- "./build.sh"

after_success:
- "./release.sh"
